//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackstopSampleAppForDocumentUpload.BackstopWidgetService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://backstopsolutions.com/BackstopService", ConfigurationName="BackstopWidgetService.BackstopWidgetService_1_0PortType")]
    public interface BackstopWidgetService_1_0PortType {
        
        // CODEGEN: Generating message contract since message getAllWidgetDefinitionsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BackstopSampleAppForDocumentUpload.BackstopWidgetService.getAllWidgetDefinitionsResponse getAllWidgetDefinitions(BackstopSampleAppForDocumentUpload.BackstopWidgetService.getAllWidgetDefinitionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BackstopSampleAppForDocumentUpload.BackstopWidgetService.getAllWidgetDefinitionsResponse> getAllWidgetDefinitionsAsync(BackstopSampleAppForDocumentUpload.BackstopWidgetService.getAllWidgetDefinitionsRequest request);
        
        // CODEGEN: Generating message contract since message getWidgetRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BackstopSampleAppForDocumentUpload.BackstopWidgetService.getWidgetResponse getWidget(BackstopSampleAppForDocumentUpload.BackstopWidgetService.getWidgetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BackstopSampleAppForDocumentUpload.BackstopWidgetService.getWidgetResponse> getWidgetAsync(BackstopSampleAppForDocumentUpload.BackstopWidgetService.getWidgetRequest request);
        
        // CODEGEN: Generating message contract since message getWidgetDefinitionRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BackstopSampleAppForDocumentUpload.BackstopWidgetService.getWidgetDefinitionResponse getWidgetDefinition(BackstopSampleAppForDocumentUpload.BackstopWidgetService.getWidgetDefinitionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BackstopSampleAppForDocumentUpload.BackstopWidgetService.getWidgetDefinitionResponse> getWidgetDefinitionAsync(BackstopSampleAppForDocumentUpload.BackstopWidgetService.getWidgetDefinitionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://backstopsolutions.com/BackstopService")]
    public partial class LoginInfoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://returnentity.webservice.fundbutter.backstopsolutions.com")]
    public partial class WidgetResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[][] dataField;
        
        private string[] namesField;
        
        private string[] typesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString", Namespace="http://backstopsolutions.com/BackstopService")]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://backstopsolutions.com/BackstopService", NestingLevel=1)]
        public string[][] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://backstopsolutions.com/BackstopService")]
        public string[] names {
            get {
                return this.namesField;
            }
            set {
                this.namesField = value;
                this.RaisePropertyChanged("names");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://backstopsolutions.com/BackstopService")]
        public string[] types {
            get {
                return this.typesField;
            }
            set {
                this.typesField = value;
                this.RaisePropertyChanged("types");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://returnentity.webservice.fundbutter.backstopsolutions.com")]
    public partial class FieldValuePair : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fieldField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://returnentity.webservice.fundbutter.backstopsolutions.com")]
    public partial class WidgetDefinition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FieldValuePair[] inputsField;
        
        private string nameField;
        
        private string[] outputColumnNamesField;
        
        private string[] outputColumnTypesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        public FieldValuePair[] inputs {
            get {
                return this.inputsField;
            }
            set {
                this.inputsField = value;
                this.RaisePropertyChanged("inputs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://backstopsolutions.com/BackstopService")]
        public string[] outputColumnNames {
            get {
                return this.outputColumnNamesField;
            }
            set {
                this.outputColumnNamesField = value;
                this.RaisePropertyChanged("outputColumnNames");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://backstopsolutions.com/BackstopService")]
        public string[] outputColumnTypes {
            get {
                return this.outputColumnTypesField;
            }
            set {
                this.outputColumnTypesField = value;
                this.RaisePropertyChanged("outputColumnTypes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllWidgetDefinitions", WrapperNamespace="http://backstopsolutions.com/BackstopService", IsWrapped=true)]
    public partial class getAllWidgetDefinitionsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://backstopsolutions.com/BackstopService")]
        public BackstopSampleAppForDocumentUpload.BackstopWidgetService.LoginInfoType LoginInfo;
        
        public getAllWidgetDefinitionsRequest() {
        }
        
        public getAllWidgetDefinitionsRequest(BackstopSampleAppForDocumentUpload.BackstopWidgetService.LoginInfoType LoginInfo) {
            this.LoginInfo = LoginInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllWidgetDefinitionsResponse", WrapperNamespace="http://backstopsolutions.com/BackstopService", IsWrapped=true)]
    public partial class getAllWidgetDefinitionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://backstopsolutions.com/BackstopService", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://returnentity.webservice.fundbutter.backstopsolutions.com")]
        public BackstopSampleAppForDocumentUpload.BackstopWidgetService.WidgetDefinition[] @out;
        
        public getAllWidgetDefinitionsResponse() {
        }
        
        public getAllWidgetDefinitionsResponse(BackstopSampleAppForDocumentUpload.BackstopWidgetService.WidgetDefinition[] @out) {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getWidget", WrapperNamespace="http://backstopsolutions.com/BackstopService", IsWrapped=true)]
    public partial class getWidgetRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://backstopsolutions.com/BackstopService")]
        public BackstopSampleAppForDocumentUpload.BackstopWidgetService.LoginInfoType LoginInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://backstopsolutions.com/BackstopService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://backstopsolutions.com/BackstopService", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://returnentity.webservice.fundbutter.backstopsolutions.com")]
        public BackstopSampleAppForDocumentUpload.BackstopWidgetService.FieldValuePair[] config;
        
        public getWidgetRequest() {
        }
        
        public getWidgetRequest(BackstopSampleAppForDocumentUpload.BackstopWidgetService.LoginInfoType LoginInfo, string name, BackstopSampleAppForDocumentUpload.BackstopWidgetService.FieldValuePair[] config) {
            this.LoginInfo = LoginInfo;
            this.name = name;
            this.config = config;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getWidgetResponse", WrapperNamespace="http://backstopsolutions.com/BackstopService", IsWrapped=true)]
    public partial class getWidgetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://backstopsolutions.com/BackstopService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BackstopSampleAppForDocumentUpload.BackstopWidgetService.WidgetResult @out;
        
        public getWidgetResponse() {
        }
        
        public getWidgetResponse(BackstopSampleAppForDocumentUpload.BackstopWidgetService.WidgetResult @out) {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getWidgetDefinition", WrapperNamespace="http://backstopsolutions.com/BackstopService", IsWrapped=true)]
    public partial class getWidgetDefinitionRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://backstopsolutions.com/BackstopService")]
        public BackstopSampleAppForDocumentUpload.BackstopWidgetService.LoginInfoType LoginInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://backstopsolutions.com/BackstopService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name;
        
        public getWidgetDefinitionRequest() {
        }
        
        public getWidgetDefinitionRequest(BackstopSampleAppForDocumentUpload.BackstopWidgetService.LoginInfoType LoginInfo, string name) {
            this.LoginInfo = LoginInfo;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getWidgetDefinitionResponse", WrapperNamespace="http://backstopsolutions.com/BackstopService", IsWrapped=true)]
    public partial class getWidgetDefinitionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://backstopsolutions.com/BackstopService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BackstopSampleAppForDocumentUpload.BackstopWidgetService.WidgetDefinition @out;
        
        public getWidgetDefinitionResponse() {
        }
        
        public getWidgetDefinitionResponse(BackstopSampleAppForDocumentUpload.BackstopWidgetService.WidgetDefinition @out) {
            this.@out = @out;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BackstopWidgetService_1_0PortTypeChannel : BackstopSampleAppForDocumentUpload.BackstopWidgetService.BackstopWidgetService_1_0PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BackstopWidgetService_1_0PortTypeClient : System.ServiceModel.ClientBase<BackstopSampleAppForDocumentUpload.BackstopWidgetService.BackstopWidgetService_1_0PortType>, BackstopSampleAppForDocumentUpload.BackstopWidgetService.BackstopWidgetService_1_0PortType {
        
        public BackstopWidgetService_1_0PortTypeClient() {
        }
        
        public BackstopWidgetService_1_0PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BackstopWidgetService_1_0PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BackstopWidgetService_1_0PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BackstopWidgetService_1_0PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BackstopSampleAppForDocumentUpload.BackstopWidgetService.getAllWidgetDefinitionsResponse BackstopSampleAppForDocumentUpload.BackstopWidgetService.BackstopWidgetService_1_0PortType.getAllWidgetDefinitions(BackstopSampleAppForDocumentUpload.BackstopWidgetService.getAllWidgetDefinitionsRequest request) {
            return base.Channel.getAllWidgetDefinitions(request);
        }
        
        public BackstopSampleAppForDocumentUpload.BackstopWidgetService.WidgetDefinition[] getAllWidgetDefinitions(BackstopSampleAppForDocumentUpload.BackstopWidgetService.LoginInfoType LoginInfo) {
            BackstopSampleAppForDocumentUpload.BackstopWidgetService.getAllWidgetDefinitionsRequest inValue = new BackstopSampleAppForDocumentUpload.BackstopWidgetService.getAllWidgetDefinitionsRequest();
            inValue.LoginInfo = LoginInfo;
            BackstopSampleAppForDocumentUpload.BackstopWidgetService.getAllWidgetDefinitionsResponse retVal = ((BackstopSampleAppForDocumentUpload.BackstopWidgetService.BackstopWidgetService_1_0PortType)(this)).getAllWidgetDefinitions(inValue);
            return retVal.@out;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BackstopSampleAppForDocumentUpload.BackstopWidgetService.getAllWidgetDefinitionsResponse> BackstopSampleAppForDocumentUpload.BackstopWidgetService.BackstopWidgetService_1_0PortType.getAllWidgetDefinitionsAsync(BackstopSampleAppForDocumentUpload.BackstopWidgetService.getAllWidgetDefinitionsRequest request) {
            return base.Channel.getAllWidgetDefinitionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BackstopSampleAppForDocumentUpload.BackstopWidgetService.getAllWidgetDefinitionsResponse> getAllWidgetDefinitionsAsync(BackstopSampleAppForDocumentUpload.BackstopWidgetService.LoginInfoType LoginInfo) {
            BackstopSampleAppForDocumentUpload.BackstopWidgetService.getAllWidgetDefinitionsRequest inValue = new BackstopSampleAppForDocumentUpload.BackstopWidgetService.getAllWidgetDefinitionsRequest();
            inValue.LoginInfo = LoginInfo;
            return ((BackstopSampleAppForDocumentUpload.BackstopWidgetService.BackstopWidgetService_1_0PortType)(this)).getAllWidgetDefinitionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BackstopSampleAppForDocumentUpload.BackstopWidgetService.getWidgetResponse BackstopSampleAppForDocumentUpload.BackstopWidgetService.BackstopWidgetService_1_0PortType.getWidget(BackstopSampleAppForDocumentUpload.BackstopWidgetService.getWidgetRequest request) {
            return base.Channel.getWidget(request);
        }
        
        public BackstopSampleAppForDocumentUpload.BackstopWidgetService.WidgetResult getWidget(BackstopSampleAppForDocumentUpload.BackstopWidgetService.LoginInfoType LoginInfo, string name, BackstopSampleAppForDocumentUpload.BackstopWidgetService.FieldValuePair[] config) {
            BackstopSampleAppForDocumentUpload.BackstopWidgetService.getWidgetRequest inValue = new BackstopSampleAppForDocumentUpload.BackstopWidgetService.getWidgetRequest();
            inValue.LoginInfo = LoginInfo;
            inValue.name = name;
            inValue.config = config;
            BackstopSampleAppForDocumentUpload.BackstopWidgetService.getWidgetResponse retVal = ((BackstopSampleAppForDocumentUpload.BackstopWidgetService.BackstopWidgetService_1_0PortType)(this)).getWidget(inValue);
            return retVal.@out;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BackstopSampleAppForDocumentUpload.BackstopWidgetService.getWidgetResponse> BackstopSampleAppForDocumentUpload.BackstopWidgetService.BackstopWidgetService_1_0PortType.getWidgetAsync(BackstopSampleAppForDocumentUpload.BackstopWidgetService.getWidgetRequest request) {
            return base.Channel.getWidgetAsync(request);
        }
        
        public System.Threading.Tasks.Task<BackstopSampleAppForDocumentUpload.BackstopWidgetService.getWidgetResponse> getWidgetAsync(BackstopSampleAppForDocumentUpload.BackstopWidgetService.LoginInfoType LoginInfo, string name, BackstopSampleAppForDocumentUpload.BackstopWidgetService.FieldValuePair[] config) {
            BackstopSampleAppForDocumentUpload.BackstopWidgetService.getWidgetRequest inValue = new BackstopSampleAppForDocumentUpload.BackstopWidgetService.getWidgetRequest();
            inValue.LoginInfo = LoginInfo;
            inValue.name = name;
            inValue.config = config;
            return ((BackstopSampleAppForDocumentUpload.BackstopWidgetService.BackstopWidgetService_1_0PortType)(this)).getWidgetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BackstopSampleAppForDocumentUpload.BackstopWidgetService.getWidgetDefinitionResponse BackstopSampleAppForDocumentUpload.BackstopWidgetService.BackstopWidgetService_1_0PortType.getWidgetDefinition(BackstopSampleAppForDocumentUpload.BackstopWidgetService.getWidgetDefinitionRequest request) {
            return base.Channel.getWidgetDefinition(request);
        }
        
        public BackstopSampleAppForDocumentUpload.BackstopWidgetService.WidgetDefinition getWidgetDefinition(BackstopSampleAppForDocumentUpload.BackstopWidgetService.LoginInfoType LoginInfo, string name) {
            BackstopSampleAppForDocumentUpload.BackstopWidgetService.getWidgetDefinitionRequest inValue = new BackstopSampleAppForDocumentUpload.BackstopWidgetService.getWidgetDefinitionRequest();
            inValue.LoginInfo = LoginInfo;
            inValue.name = name;
            BackstopSampleAppForDocumentUpload.BackstopWidgetService.getWidgetDefinitionResponse retVal = ((BackstopSampleAppForDocumentUpload.BackstopWidgetService.BackstopWidgetService_1_0PortType)(this)).getWidgetDefinition(inValue);
            return retVal.@out;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BackstopSampleAppForDocumentUpload.BackstopWidgetService.getWidgetDefinitionResponse> BackstopSampleAppForDocumentUpload.BackstopWidgetService.BackstopWidgetService_1_0PortType.getWidgetDefinitionAsync(BackstopSampleAppForDocumentUpload.BackstopWidgetService.getWidgetDefinitionRequest request) {
            return base.Channel.getWidgetDefinitionAsync(request);
        }
        
        public System.Threading.Tasks.Task<BackstopSampleAppForDocumentUpload.BackstopWidgetService.getWidgetDefinitionResponse> getWidgetDefinitionAsync(BackstopSampleAppForDocumentUpload.BackstopWidgetService.LoginInfoType LoginInfo, string name) {
            BackstopSampleAppForDocumentUpload.BackstopWidgetService.getWidgetDefinitionRequest inValue = new BackstopSampleAppForDocumentUpload.BackstopWidgetService.getWidgetDefinitionRequest();
            inValue.LoginInfo = LoginInfo;
            inValue.name = name;
            return ((BackstopSampleAppForDocumentUpload.BackstopWidgetService.BackstopWidgetService_1_0PortType)(this)).getWidgetDefinitionAsync(inValue);
        }
    }
}
